name: "CI: Synchronize Labels"
on:
  push:
    branches:
      - "master"
    paths:
      - ".github/labels.yml"
      - ".github/workflows/ci-label.yml"
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: "[INIT] Checkout repository"
        uses: actions/checkout@v5
      - name: "[EXEC] Synchronize labels"
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
